### ISSUE TITLE
Chunk not processed in 1.7.0

### ISSUE THREAD

**Issue by ernestoe** [tilo/smarter_csv#195] opened 2022-07-01 20:42 UTC
The following code works fine in `1.6.1`, but doesn't process a single chunk in `1.7.0`.
The block provided does not execute at all and thus `chunk_count` remains at 0.

Am I missing something? 

```
  def self.csv_import
    options = { chunk_size: 100 }
    chunk_count = 0
    SmarterCSV.process(Style.csv_path, options) do |chunk|
      sleep(1)
      GenericProcessChunkJob.perform_later('Style', chunk)
      chunk_count += 1
    end
    chunk_count
  end
```

**Comment by tilo** [comment] 2022-07-02 17:44
@ernestoe thank you for posting - will have a look!

**Comment by tilo** [comment] 2022-07-03 01:44
@ernestoe I can not reproduce this. 

Can you please have a look at [this RSpec test](https://github.com/tilo/smarter_csv/blob/c807e30a0d875fbdb2c1257f64ec8668f8b8dd09/spec/smarter_csv/chunked_spec.rb#L29)

I'd appreciate if you could write a test which reproduces the issue

**Comment by tilo** [comment] 2022-07-03 02:01
if your `GenericProcessChunkJob.perform_later` raises an exception, the chunk does not get counted.. 
What happens if `chunk_count += 1` is placed right after the `sleep` statement?

**Comment by tilo** [comment] 2022-07-06 15:38
@ernestoe were you able to reproduce this, and create a test? Or should I close this?

**Comment by KXEinc** [comment] 2022-07-06 23:13
if `remove_empty_values: true` (by default) and this is the Rails app, nothing after line 100 executes including `yield` on line 140.
 
 I think ternary operator fits on the line 100 the best:
 `has_rails ? hash.delete_if{|_k, v| v.blank?} : hash.delete_if{|_k, v| blank?(v)}`
 
https://github.com/tilo/smarter_csv/blob/9826bfdbc93fd3ace45c61d9a8312f35b4f2d512/lib/smarter_csv.rb#L100

**Comment by ernestoe** [comment] 2022-07-07 00:35
@tilo, sorry for the delay, let me try to put together the test... and your comment on `chunk_count`

**Comment by ernestoe** [comment] 2022-07-07 01:35
If I include my `rails_helper` in the provided RSpec test

```
require 'rails_helper'
```

the test fails. And it's mostly standard configuration.

**Comment by KXEinc** [comment] 2022-07-07 14:13
It looks like version `1.6.0` does not have `return`:
https://github.com/tilo/smarter_csv/compare/v1.6.0...v1.7.0#diff-4b823c212caa561f9ac49a3a0c4f8a04494869fd234e4475f71241dd1b8ff183L94-R101

**Comment by ernestoe** [comment] 2022-07-26 00:13
@tilo is this on the right track? Do you consider it properly identified?

**Comment by n-rodriguez** [comment] 2022-07-28 23:08
You should not return while you're in a loop :

https://github.com/tilo/smarter_csv/blob/8c35567247074837169d7a8aef4e913e10492d1d/lib/smarter_csv.rb#L59
https://github.com/tilo/smarter_csv/blob/8c35567247074837169d7a8aef4e913e10492d1d/lib/smarter_csv.rb#L100

The previous version of this code was better :

https://github.com/tilo/smarter_csv/blob/v1.6.1/lib/smarter_csv/smarter_csv.rb#L94

or the proposed one :

```ruby
 hash.delete_if { |_k, v| has_rails ? v.blank? : blank?(v) }
```

**Comment by tilo** [comment] 2022-07-31 16:25
@n-rodriguez thank you for pointing this out!

Will release 1.7.1 today

**Comment by n-rodriguez** [comment] 2022-07-31 18:40
@tilo thank you!

**Comment by tilo** [comment] 2022-07-31 20:27
@n-rodriguez @ernestoe @KXEinc Thank you for your input on this!

Sorry for introducing this in 1.7.0 

hat can I say? 
I've been indoctrinated by Rubocop with having to use guard clauses - that I put one in place where it didn't belong 🤦‍♂️ 

What was really weird for this bug is that on OSX M1 architecture this ran all the tests successfully 😮 When I ran it on an old OSX X86 architecture, there were failed tests.
Never seen this kind of test behavior before.

**Comment by tilo** [comment] 2022-07-31 20:32
Bugfix release 1.7.1 was just published

Please re-evaluate and update this issue if this fixes the problem

**Comment by n-rodriguez** [comment] 2022-07-31 20:35
@tilo it works! thank you!

**Comment by tilo** [comment] 2022-07-31 20:49
Thank you all for your patience!

I'll work on adding a Rails related test

**Closed by tilo** 2022-07-31 20:49 UTC
